[package]
name = "rust_binds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name         = "rust_binds"
crate-type   = ["rlib", "cdylib"]

[dependencies]
libc = "0.2.85"
